Updating version so that multiple builds can be done

diff --git a/.github/workflows/build-android.yml b/.github/workflows/build-android.yml
--- a/.github/workflows/build-android.yml
+++ b/.github/workflows/build-android.yml
@@ -76,12 +76,24 @@ jobs:
           echo -n "$ANDROID_KEY_PROPERTIES" | base64 --decode -o $KEY_PROPERTIES_FILE
           echo -n "$ANDROID_UPLOAD_KEY_JKS" | base64 --decode -o $UPLOAD_KEY_JKS_FILE
 
+      - name: Update Version Code in Android build
+        working-directory: ./android
+        run: |
+          # Get curent version from build.gradle
+          VERSION_CODE=$(grep versionCode ./build.gradle | awk '{print $2}') || error "Failed to read Android versionCode"
+          # Tack on the date including the hour and min
+          VERSION_CODE="$VERSION_CODE_$(date '+%Y%m%d%H%M')""
+          
+          # Update capacitor.config.json version code
+          sed -i "" "s/versionCode .*/versionCode $VERSION_CODE/" ./build.gradle || error "Failed to update Android versionCode"
+          
       - name: npm build-mobile
         run: npm run build-mobile
 
-      # outputs to:
-      # ./app/build/outputs/apk/release/app-release.apk
-      # ./app/build/outputs/apk/debug/app-debug.apk
+        # outputs to:
+        # ./app/build/outputs/apk/release/app-release.apk
+        # ./app/build/outputs/apk/debug/app-debug.apk
+
       - name: Build Project
         working-directory: ./android
         run: ./gradlew build
