Fixing version code update in github workflow

diff --git a/.github/workflows/build-android.yml b/.github/workflows/build-android.yml
--- a/.github/workflows/build-android.yml
+++ b/.github/workflows/build-android.yml
@@ -79,13 +79,15 @@ jobs:
       - name: Update Version Code in Android build
         working-directory: ./android
         run: |
+          GRADLE_FILE=./app/build/.gradle
+
           # Get curent version from build.gradle
-          VERSION_CODE=$(grep versionCode ./build.gradle | awk '{print $2}') || error "Failed to read Android versionCode"
+          VERSION_CODE=$(grep versionCode $GRADLE_FILE | awk '{print $2}') || error "Failed to read Android versionCode"
           # Tack on the date including the hour and min
-          VERSION_CODE="$VERSION_CODE_$(date '+%Y%m%d%H%M')""
+          DATE_CODE=$(date '+%Y%m%d%H%M')
           
           # Update capacitor.config.json version code
-          sed -i "" "s/versionCode .*/versionCode $VERSION_CODE/" ./build.gradle || error "Failed to update Android versionCode"
+          sed -i "" "s/versionCode .*/versionCode ${VERSION_CODE}.${DATE_CODE}/" $GRADLE_FILE || error "Failed to update Android versionCode"
           
       - name: npm build-mobile
         run: npm run build-mobile
